spring.application.name=mdbm

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#MySQL Properties
spring.datasource.mysql.url=jdbc:mysql://localhost:3306/mdbm_project
spring.datasource.mysql.username=root
spring.datasource.mysql.password=Incedo@1234
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mongodb.uri=mongodb://localhost:27017/mdbm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ADD THESE ↓
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://localhost:3306/mdbm_project
spring.datasource.username=root
spring.datasource.password=Incedo@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver